# Generated by Django 2.0.4 on 2018-04-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='prescription_reminder',
            new_name='medicine_reminder',
        ),
    ]
