# Generated by Django 2.0.4 on 2018-04-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20180424_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
