# Generated by Django 2.0.4 on 2018-04-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20180424_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['prescription_reminder']},
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='medicine_reminder',
            new_name='prescription_reminder',
        ),
    ]
