# Generated by Django 2.0.4 on 2018-04-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20180424_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['medicine_reminder']},
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='prescription_reminder',
            new_name='medicine_reminder',
        ),
    ]
