# Generated by Django 2.0.7 on 2018-07-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        # ~ migrations.RemoveField(
            # ~ model_name='visit',
            # ~ name='medicine_payment',
        # ~ ),
        # ~ migrations.RemoveField(
            # ~ model_name='visit',
            # ~ name='visit_payment',
        # ~ ),
    ]
