# Generated by Django 2.0.4 on 2018-04-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='prescription',
            name='medicine_dose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.Dose'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.Reminder'),
        ),
    ]
