# Generated by Django 2.0.4 on 2018-04-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20180425_1536'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='medicine',
            #name='prescription_reminder',
        #),
    ]
