# Generated by Django 2.0.4 on 2018-04-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_remove_medicine_prescription_reminder'),
    ]

    operations = [

    ]
