# Generated by Django 2.0.4 on 2018-04-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_remove_medicine_prescription_reminder'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='medicine',
            #name='medicine_dose',
        #),
        #migrations.RemoveField(
            #model_name='medicine',
            #name='medicine_quantity',
        #),
        #migrations.RemoveField(
            #model_name='medicine',
            #name='prescription_reminder',
        #),
    ]
