# Generated by Django 2.0.4 on 2018-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20180425_1826'),
    ]

    operations = [
        # migrations.RemoveField(
            # model_name='medicine',
            # name='medicine_dose',
        # ),
        # migrations.RemoveField(
            # model_name='medicine',
            # name='medicine_quantity',
        # ),
        # migrations.RemoveField(
            # model_name='medicine',
            # name='prescription_reminder',
        # ),
    ]
