# Generated by Django 2.0.4 on 2018-04-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20180428_1702'),
    ]

    operations = [
        # migrations.RemoveField(
            # model_name='medicine',
            # name='medicine_dose',
        # ),
        # migrations.RemoveField(
            # model_name='medicine',
            # name='medicine_quantity',
        # ),
        # migrations.RemoveField(
            # model_name='medicine',
            # name='prescription_reminder',
        # ),
    ]
