# Generated by Django 2.0.3 on 2018-03-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_remove_patient_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('dr_id', models.AutoField(primary_key=True, serialize=False)),
                ('dr_name', models.CharField(max_length=55)),
                ('dr_suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('dr_telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('dr_lic_no', models.CharField(blank=True, max_length=25, null=True)),
                ('dr_ptr_no', models.CharField(blank=True, max_length=25, null=True)),
                ('dr_s2_no', models.CharField(blank=True, max_length=25, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['-counter'],
            },
        ),
        migrations.CreateModel(
            name='DrOfficeHour',
            fields=[
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(blank=True, max_length=20, null=True)),
                ('hours_am', models.CharField(blank=True, max_length=20, null=True)),
                ('hours_pm', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['-counter'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hosp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('hosp_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hosp_city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.Town')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['-counter'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='dr_afil',
            field=models.ManyToManyField(blank=True, max_length=25, to='doctor.Hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dr_off_hour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.DrOfficeHour'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
