# Generated by Django 2.0.4 on 2018-05-02 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=' ', max_length=25)),
                ('last_name', models.CharField(default=' ', max_length=20)),
                ('suffix', models.CharField(default='M.D.', max_length=55)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('lic_no', models.CharField(blank=True, max_length=25, null=True)),
                ('ptr_no', models.CharField(blank=True, max_length=25, null=True)),
                ('s2_no', models.CharField(blank=True, max_length=25, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
